# The characters that will be used to construct the hints.
# Character at the beginning of the list have priority in
# hint generation.
# Defaults to "fdsajkl;weiocmruvnghqpxztyb" if not specified.
hint_characters: fdsajkl;weiocmruvnghqpxztyb
# The list of different selection modes. Currently, only
# the first mode is used.
modes:
  # The type of the mode. Currently, the only supported type
  # is "regex" which accepts a list of regular expressions
  # and uses them to select the text.
  - mode: regex
    # This hotkey can be pressed to select this mode during
    # mode selection. Each mode should have a unique hotkey.
    hotkey: r
    # This name will be shown along with the hotkey during
    # mode selection.
    name: default
    # The list of regular expressions to use for matching.
    # Note that lookaround is not supported.
    regexes:
      - '[\w._\-~/]{4,}'
