# The characters that will be used to construct the hints.
# Characters at the beginning of the list have priority in
# hint generation.
hint_characters: fdsajkl;weiocmruvnghqpxztyb

# Style to use for hints (keys to press to select) displayed
# during selection.
# See "COLORS" section in help for details on specifying colors.
hint_bg: 5;208
hint_fg: 5;232

# Style to use for highlights (what will be selected when hint
# keys are pressed) displayed during selection.
highlight_bg: 5;232
highlight_fg: 5;252

# Color to use for the divider used during mode switching
mode_switch_divider_fg: 5;208
# Color to use for the hotkeys inside the mode switching panel
mode_switch_hotkey_fg: 5;208
# Color to use for the mode names inside the mode switching panel
mode_switch_mode_name_fg: 5;252

# Width of the mode switching dialog, including the divier character
mode_switch_width: 25

# The list of different selection modes.
modes:
  # The type of the mode. Currently, the only supported type
  # is "regex" which accepts a list of regular expressions
  # and uses them to select the text.
  - mode: regex
    # This hotkey can be pressed to select this mode during
    # mode selection. Each mode should have a unique hotkey.
    hotkey: r
    # This name will be shown along with the hotkey during
    # mode selection.
    name: default
    # The list of regular expressions to use for matching.
    # Note that lookaround is not supported.
    regexes:
      - '[\w._\-~/]{4,}'
